### ISSUE TITLE
[bug] exchange_code_for_token throws a parse error

### ISSUE THREAD

**Issue by joshkestenberg** [nylas/nylas-ruby#278] opened 2021-03-10 20:09 UTC
`> client.exchange_code_for_token('FAKE')`

throws:
```
Traceback (most recent call last):
        1: from (irb):81
Yajl::ParseError (lexical error: invalid char in json text.)
                                       <html> <head>     <meta http-eq
                     (right here) ------^
```

**Comment by arunagw** [comment] 2021-04-08 16:53
@joshkestenberg thanks for reporting this. I just gave it a try on my side and unable to reproduce this. Can you please give it a try and see if it's still an issue for you? I get `Nylas::UnexpectedResponse`

**Comment by joshkestenberg** [comment] 2021-04-08 17:10
Appears to be the same:

 `Nylas::API.new(app_id: ENV['NYLAS_APP_ID'], app_secret: ENV['NYLAS_APP_SECRET']).exchange_code_for_token('FAKE')`
 ```
Traceback (most recent call last):
        1: from (irb):10
Yajl::ParseError (lexical error: invalid char in json text.)
                                       <html> <head>     <meta http-eq
                     (right here) ------^
```

**Comment by arunagw** [comment] 2021-04-09 14:30
On which version of gem you are getting this error?

**Comment by joshkestenberg** [comment] 2021-04-09 14:39
looks like we're at v4.6.3

**Comment by arunagw** [comment] 2021-04-14 17:36
Closing this issue for now. Please reopen and report back here if it's still an issue. thanks

**Closed by arunagw** 2021-04-14 17:36 UTC
