### ISSUE TITLE
Exception message: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by 3mammoth** [nylas/nylas-ruby#86] opened 2016-10-04 22:13 UTC
![image](https://cloud.githubusercontent.com/assets/4804082/19094473/1bde75a6-8a45-11e6-8353-d4441a5a260d.png)

**Comment by 3mammoth** [comment] 2016-10-04 22:14
Linen 289 of nylas.rb has bug. For some reason it's possible for the json['deltas'] to be nil there.

**Comment by pfista** [comment] 2016-10-31 19:28
My best guess is that we failed to properly throw an error when interpreting the API response.  This should be fixed in 55b9d6287371d0d35e5077846e5127f6d000ec34, but without more information I can't help here. Closing this out but feel free to provide more info if the issue is still there in the next 3.0.0 release.

**Closed by pfista** 2016-10-31 19:28 UTC
